import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface TermsPageProps {
  onNavigate: (path: string) => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-8">
      <button
        onClick={() => onNavigate('/')}
        className="text-xs font-semibold text-blue-600 hover:underline inline-flex items-center gap-1"
      >
        <ArrowLeft className="w-3.5 h-3.5" /> Return to Home
      </button>

      <div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900">
          Terms of Service
        </h1>
        <p className="text-xs text-slate-500 mt-2 font-mono">
          Last Updated: January 15, 2025
        </p>
      </div>

      <div className="prose prose-slate max-w-none text-slate-700 text-sm leading-relaxed space-y-6">
        <p>
          Welcome to <strong>CodeNova</strong>. These Terms of Service ("Terms") govern your use of our website, estimation calculators, and client engagement agreements. By accessing this site or commissioning custom engineering services, you agree to these Terms.
        </p>

        <h3 className="text-lg font-bold text-slate-900">1. Intellectual Property & Code Ownership</h3>
        <p>
          Upon full payment of agreed project milestones, 100% of bespoke source code, database schemas, custom UI/UX assets, and deployment scripts created exclusively for the client are assigned unconditionally to the client. CodeNova retains no claim to your proprietary business logic.
        </p>

        <h3 className="text-lg font-bold text-slate-900">2. Estimator & Ballpark Scoping</h3>
        <p>
          Calculations generated by the CodeNova Project Estimator represent indicative ranges based on standard industry engineering hours. Formal binding commercial proposals require an executed Scope of Work (SOW) following Phase 01 Discovery.
        </p>

        <h3 className="text-lg font-bold text-slate-900">3. Warranties & SLA Support</h3>
        <p>
          CodeNova warrants that all custom deliverables will perform substantially in accordance with the agreed technical specifications for a period of thirty (30) to sixty (60) days following production deployment. Extended guarantees are provided under active SLA maintenance agreements.
        </p>

        <h3 className="text-lg font-bold text-slate-900">4. Contact</h3>
        <p>
          For legal inquiries regarding contracts and IP assignment, please reach out to <a href="mailto:legal@codenova.tech" className="text-blue-600 underline">legal@codenova.tech</a>.
        </p>
      </div>
    </div>
  );
};
